language: node_js
node_js:
    - 8
cache: npm
install:
    - npm install -g npm@latest
    - npm --version
    - npm install --registry http://registry.npmjs.org
    - npm install -g codecov
script:
    - npm link
    - npm run test
    - codecov